import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Dynamic routing next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my app
        </h1>
        <div>
            <Link href="/joke/categories">categories of jokes</Link>
          </div>
          <div>
            <Link href="/joke/category">joke from a given category </Link>
          </div>
      </main>
    </div> 
    </Layout>
    </>
  )
}

export default Home;